# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-02 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='action_type_id',
            new_name='action_type',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='match_id',
            new_name='match',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='player_id',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='team_id',
            new_name='team',
        ),
    ]
