# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-06 19:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20170902_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='birth',
            field=models.DateField(default=datetime.datetime(2017, 10, 6, 19, 34, 21, 805803)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='height',
            field=models.PositiveIntegerField(default=180),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='passport',
            field=models.CharField(default=datetime.datetime(2017, 10, 6, 19, 36, 0, 686729), max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(default=datetime.datetime(2017, 10, 6, 19, 36, 19, 478874), max_length=100),
            preserve_default=False,
        ),
    ]
