# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-17 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20171006_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='short_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
    ]
