# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-28 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_match_fiba_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action_subtype',
            name='parent',
        ),
    ]
