# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-02 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0009_auto_20171228_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.Player'),
        ),
    ]
