# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-07 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0010_auto_20180102_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='short_name',
            field=models.CharField(max_length=100),
        ),
    ]
