# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-14 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0012_auto_20180108_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.DateField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='action',
            name='player',
        ),
        migrations.RemoveField(
            model_name='action',
            name='team',
        ),
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
        migrations.AddField(
            model_name='teamplayer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Player'),
        ),
        migrations.AddField(
            model_name='teamplayer',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Team'),
        ),
        migrations.AddField(
            model_name='action',
            name='teamplayer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.TeamPlayer'),
        ),
    ]
