# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-18 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0013_auto_20180114_1126'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamPlayer',
            new_name='Team_Player',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='teamplayer',
            new_name='Team_Player',
        ),
    ]
