# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-18 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0014_auto_20180118_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='Team_Player',
            new_name='teamplayer',
        ),
    ]
