# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-20 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0015_auto_20180118_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_sets', models.ManyToManyField(blank=True, null=True, to='stats.Team_Player')),
            ],
        ),
    ]
