# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-20 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0016_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='player_sets',
            field=models.ManyToManyField(to='stats.Team_Player'),
        ),
    ]
