# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-20 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0017_auto_20180120_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='set',
            old_name='player_sets',
            new_name='players_set',
        ),
    ]
