# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-21 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0018_auto_20180120_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='set',
            old_name='players_set',
            new_name='teamplayers_set',
        ),
    ]
